name: funktionstest
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/checkout@v4
      - run: pip install numpy pytest pytest-cov
      - run: pytest --cov-report=term --cov=spiellogik.py
