name: lernend_vs_stochastisch
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
      - run: |
              pip install numpy numba
              python skripte/lernskript.py
      - uses: actions/upload-artifact@v4
        with:
          path: reversi.zip/
          compression-level: 0
          overwrite: true
