name: optimierend_vs_stochastisch
on:
  workflow_dispatch:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with: 
          lfs: true
      - run: |
              pip install numpy numba
              git lfs checkout *.of
              git lfs pull
              python skripte/optimierend_vs_stochastisch.py 100000 100
      - uses: actions/upload-artifact@v4
        with:
          path: neu.of
          compression-level: 6
          overwrite: true
